# Generated by Django 5.2.3 on 2025-07-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
