# Generated by Django 5.2.3 on 2025-07-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_factura_bloqueada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ubicaciones/'),
        ),
    ]
