# Generated by Django 5.2.3 on 2025-07-05 21:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_factura_hora_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=api.models.obtener_fecha_actual),
        ),
        migrations.AlterField(
            model_name='factura',
            name='hora',
            field=models.TimeField(default=api.models.obtener_hora_actual),
        ),
    ]
